app:
  message: Account message successfully published to queue

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    exchange: account.exchange
    routingkey: account.routingkey

server:
  port: 8081